# Header
menu:
  Archives: /archives
  Smoke price: /price

rss: /rss2.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
sidebar: right
widgets:
- top_users
- ads
- top_tags

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-140211511-1
favicon: /favicon.png
twitter: smoke-indica
